### ISSUE TITLE
Create Development Branch

### ISSUE THREAD

**Issue by aethnae** [aethnae/vault#1]
Pretty self-explanatory!

**Comment by MarioSieg** [comment]
Was für development branch bei Obsidian Vault 😭

**Comment by MarioSieg** [comment]
![CleanShot 2024-09-13 at 13 08 35](https://github.com/user-attachments/assets/9ac25cdb-a3a2-40da-a8db-561f95b20069)

**Comment by aethnae** [comment]
warum ist das in dem repo hahahahaahaha das soll nicht hier hin
